name: Build & Deploy

on:

  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build & Push
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Github Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: Dockerfile
        push: true
        tags: |
          ghcr.io/chrisbuckleycode/hello-world:latest

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs:
      - build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy using Kubectl
      run: |
        echo "$KUBECONFIG" > .kubeconfig
        KUBECONFIG=.kubeconfig kubectl rollout restart deployment hello-world
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
